### ISSUE TITLE
Submit run modal looks blurry

### ISSUE THREAD

**Issue by zoton2** [esamarathon/user-management#12]
Discussed in our meeting, for some reason for me and Fatzke (at least) the submit run modal looks blurry, not sure why.

Example: https://cdn.discordapp.com/attachments/120881242068484097/560199194707755039/unknown.png

**Comment by Stenkilde** [comment]
After additional testing, I think it has something to do with the modal / texts landing on "subpixels".

This can happen when you do stuff sizing in %, if I change the height of the modal to be auto instead of the `max-height: 80%;` then it becomes less blurry

**Comment by Stenkilde** [comment]
Yeh looks like it's subpixel.. If you change the `translate` on the modal with the following translation it becomes super sharp

`translateX(-50%) translateY(calc(-50% - .5px))`
