### ISSUE TITLE
Error after cancelling Discord authorization 

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#19]
![Discord_2019-03-28_20-12-01](https://user-images.githubusercontent.com/48857155/55185952-c47cc900-5195-11e9-9044-bb6839075c2f.png)

**Comment by FatzkeFTW** [comment]
Authorization seems to be unable to be completed after cancelling it:
![Discord_2019-03-28_20-19-10](https://user-images.githubusercontent.com/48857155/55186439-d7dc6400-5196-11e9-83f9-120fa2a9060c.png)

**Comment by CBenni** [comment]
This should be fixed, can you validate?

**Comment by FatzkeFTW** [comment]
SeemsGood

![Discord_2019-03-28_21-55-01](https://user-images.githubusercontent.com/48857155/55192190-33611e80-51a4-11e9-87c6-f28b7127d9c0.png)

**Comment by CBenni** [comment]
Excellent
