### ISSUE TITLE
Make Discord mandatory

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#2]
Discord is the main way we contact runners and as such I'd like it to be required to be set in the profile before being able to submit games.

We had issues in the past where we had to resort to things like Twitch whispers or even YouTube messages because we couldn't find a way to reach out and it was a huge pain in the ass.

Maybe also add a message as to why it's required and a hint towards the ESA Discord when hovering over the field.

**Comment by CBenni** [comment]
Do you want membership in the ESA discord guild to be mandatory as well?

**Comment by FatzkeFTW** [comment]
It should be encouraged, but not be mandatory for now.
