### ISSUE TITLE
Cannot click on datepicker in user profile

### ISSUE THREAD

**Issue by ylorant** [esamarathon/user-management#21]
Hello (linkboss here),

When trying to edit my availability for ESA Summer, I tried changing my availability by clicking on the datepickers and, at my demise, I noticed that it wasn't possible. I don't know if it is expected from the users to type the date manually, but I think some of them will try to fill it by mouse and be quizzed by the non-responsiveness of it.

Browser : Mozilla Firefox 65.0.2 (Windows).

**Comment by gaeldemarseille** [comment]
Looks like it was fixed because now it works fine (could only select until March 28th but not it goes up to August something)

**Comment by ylorant** [comment]
I confirm it is fixed, closing.
