### ISSUE TITLE
Apple device sizing issue

### ISSUE THREAD

**Issue by pandathesenpai** [esamarathon/user-management#26]
https://imgur.com/a/QrgxZPo

Already posted to fatzke but didn't want to spam :'D so posting here anyway

It does however seem to size the activity/invitations/feed bars correctly, vs current version of Chrome making the bars go all the way down the page

**Comment by MaxieTheHatter** [comment]
Same issue is present across all mobile devices, including tablets in landscape mode, and narrow window sizes

**Comment by CBenni** [comment]
Generally, mobile friendliness needs to be improved...

**Comment by CBenni** [comment]
I have improved a lot of things since the last time I updated this issue. While mobile will never be perfect, its mostly usable™ now, I hope.
