### ISSUE TITLE
New required fields in the submission form

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#3]
I'd like the following fields to be added to the submission form:

- Leaderboard (mandatory)
Being able to access the leaderboards with one or two clicks from the submission overview page is a huge deal for us. The alternative is manually navigating to sr.com (or soulsruns/megamanleaderboards) and looking for the game, which takes a lot of time since we need to check those often. The previous form we used accessed the sr.com API to automagically insert the URL to the leaderboard when the submitted game is found on that site.
On that note: it's probably good to make a speedrun.com username in the profile mandatory as well so we have the option of navigating to that easily, too.

- Availability (not mandatory, editable until schedule release)
For runners to put in when they're at the event/able to do a run. Maybe make the wording more ambiguous so it applies to online and offline marathons. If they don't give any, we assume they're there for the entire duration. Instead of a text field this could also be the choice of the boundary dates/times for easier interface with the scheduling tool.

- Donation Incentives/Bid Wars (not mandatory, editable until marathon start)
Just a text field *shrug*. Incentives should in general not add more than 5 minutes to the total time fo the run. When justified they can go on longer in some cases. 

Other:
We can probably combine the Game description and Comment fields into one.

**Comment by CBenni** [comment]
Ah I didnt mean to close this. Leaderboard, twitch game and donation incentives/bid wars are added.

sr.com and availability are yet to be added to the profile.

**Comment by FatzkeFTW** [comment]
Regarding availability:
- Currently able to set a negative one (like July 29th to July 25th).
- Maybe also restrict the fields to the actual event dates.
- Maaaybe also encourage users to set their availability once before submitting a run or when setting up their profile

Since I don't want to add a separate issue for something this small:
- Add a text to the phone number field explaining what it would be used for. People are suspicious about that sort of thing and it would prevent constant questions on Discord. Alternatively, since it's not being used right now at all, just disable it.

**Comment by CBenni** [comment]
This should be all done now. If theres any further issues, I suggest we create a new issue (makes it easier to track)

**Comment by gaeldemarseille** [comment]
Some run might not have leaderboards (D&D or Tetris TGM)

**Comment by CBenni** [comment]
In those rare cases, which should be clarified to ESA staff, they can provide a bogus url. Keeping it as required is important to make sure the best majors of other runs have valid leaderboards set however.
