### ISSUE TITLE
Submission details page has a link to http://xn--4v8haa.xn--4v8h/

### ISSUE THREAD

**Issue by gaeldemarseille** [esamarathon/user-management#31]

**Comment by CBenni** [comment]
Can you give a more detailed description of the issue? What submission did you select?

**Comment by gaeldemarseille** [comment]
https://submissions.esamarathon.com/#/dashboard/submissions/039744050b4f8a011e8726a7
that Name links to http://xn--4v8haa.xn--4v8h/ 
![image](https://user-images.githubusercontent.com/5615080/55190604-6ef9e980-51a0-11e9-8dfe-34a7e7517650.png)

**Comment by gaeldemarseille** [comment]
Actually it didn't like my http://🔥🔥🔥.🔥 leaderboard URL

**Comment by CBenni** [comment]
Yeah this is called punycode, it happens when you have non-alphanumeric domains. This is working as intended
