### ISSUE TITLE
Editting a 4th run as editted duplicate to submit as a 5th run

### ISSUE THREAD

**Issue by pandathesenpai** [esamarathon/user-management#34]
It seems to sometimes remove incentives and bidwars, and instead submits the run as a straight up duplicate of the 4th run when hitting the submission max.

Newest version of Chrome used, phone device not tested yet

**Comment by CBenni** [comment]
Can you please elaborate on this? I dont quite understand what happened there. There is a few issues with duplication that I am working on solving as of right now (ref https://github.com/esamarathon/user-management/issues/25)

**Comment by pandathesenpai** [comment]
I was literally writing about it :D 

When you have 4 runs submitted, if you edit the 4th and/or add/remove incentives or bidwars and save it; it will either save it or it will just straight up copy the 4th submission.

Trying to reproduce the issue after several tries so probably a low prio if I get it working again, it might be my Chrome in general because it has been wonky as heck lately and I don't know why.

1st try: 
[ Editted 4th submission, editted one incentive and saved ]
[ 5th becomes a straight up copy ]

2nd try:
[ Editted 4th submission, removed incentive and saved ]
[ 5th run is fine ]

3nd try: 
[ Editted 4th submission, editted one incentive, removed one incentive, saved ]
[ 5th run becomes a straight up copy ]

**Comment by CBenni** [comment]
Were any of these runs duplicates of another?
What happened when you refreshed?

**Comment by pandathesenpai** [comment]
I've just duplicated the same run 4 times in order to try and break it.

I can duplicate and edit submission 1, 2 and 3 and it becomes a 4th submission that has everything I wanted editted.

If I duplicate and edit the 4th submission (I do not press the Submit Run button), do the changes I want done to it and then save it; it sometimes becomes a straight up copy. <- Because of this I would call it low prio but not sure if it would produce any issues down the line. You can just delete the 5th duplicated run and make a completely new one from scratch to just fix it.

I just want to note that my issues with chrome lately might be the reason, I'm even close to switching to Firefox due to how much it bugs me (Sometimes deletes whole urls, pages show certain string/lines, can't interact properly with certain site integrated stuffs)

**Comment by pandathesenpai** [comment]
Oh and refreshing doesn't seem to do anything

**Comment by pandathesenpai** [comment]
Refreshing seems to produce a copied 5th run even if I delete a run

**Comment by pandathesenpai** [comment]
Editting the run titles and refreshing just goes back to its previous state

**Comment by CBenni** [comment]
So all of these runs are not runs you set up, but duplicates of one run that you are editing?

**Comment by pandathesenpai** [comment]
This might be related to the bug I posted previously where you can edit and submit runs despite hitting the Submission limit. 

They might be hiding in the back-end of the submitted duplicated runs, but you probably fixed it already so they were still hiding on my end as I kept deleting them.

**Comment by pandathesenpai** [comment]
Update

I deleted the 5 runs displayed on my page
Refreshed
Got a return of 4 duplicated runs instead

Refreshed again and it's back to 5 so you probably did something on your end?

**Comment by pandathesenpai** [comment]
Deleted all 5 runs
submitted 3 new runs 

Refreshed

Reverts back to all 5 "duplicate" runs

**Comment by CBenni** [comment]
Can you join the discord guild so I can talk to you directly to figure out whats going on exactly? It seems like something corruped a run on your end and now it cant save things at all.

**Comment by CBenni** [comment]
So this turned out to be an issue with duplicating runs and server side validations of teams. Fixed in https://github.com/esamarathon/user-management/commit/ea6404b9f8d144c919099ad5c1424731544481aa
