### ISSUE TITLE
Site not loading using Microsoft Edge or Internet Explorer

### ISSUE THREAD

**Issue by MaxieTheHatter** [esamarathon/user-management#35]
Is probably really low on the priority list, but the site won't load at all using Microsoft browsers.

Throws the following error:
 SCRIPT1028: SCRIPT1028: Expected identifier, string or number

at location c2737b5111b3ee76717f.bundle.js (83,31555)

**Comment by CBenni** [comment]
This simply requires a different build target on my end. I will probably end up doing this eventhough it makes things slower for all users :/

**Comment by CBenni** [comment]
Fixed in https://github.com/esamarathon/user-management/commit/9863165e206a6449aa41b54ef85eb424495e618b
