### ISSUE TITLE
Unable to choose platform

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#5]
Unable to choose platform ¯\_(ツ)_/¯
![2019-03-23_14-04-01](https://user-images.githubusercontent.com/48857155/54866495-b1709000-4d74-11e9-90c6-50e987b2798e.gif)

**Comment by CBenni** [comment]
Known bug, ive been trying to fix that for a long time. For now, you can simply enter it or select it using arrow keys and enter.

**Comment by LLCoolDave** [comment]
Should be fixed now after updating the autocomplete dropdown component in #8 .
