### ISSUE TITLE
Feature Request: Commentator

### ISSUE THREAD

**Issue by FatzkeFTW** [esamarathon/user-management#72]
Ability to assign at least one dedicated commentator when submitting a run.
OPTIONAL for non-races (solo, co-op, relay)
REQUIRED for all race submissions

ESA Summer submissions start in early March.

**Comment by FatzkeFTW** [comment]
Would like this to be toggleable in case it's not necessary/used for a marathon.

**Comment by CBenni** [comment]
Can you elaborate on what this would mean? - Would people select another user similarly to the team selection system, with an approval process?

**Comment by FatzkeFTW** [comment]
Ideally yes, but it would be enough if it's an extra text field.

**Comment by CBenni** [comment]
Added in https://github.com/esamarathon/user-management/commit/8cb025de34823c6a15cabbc3f8339646680abf70
